// Modified from code generated by github.com/wishabi/kafka.go.
package generic_schema

import (
	"testing"
	// demo "github.com/DeeChau/kafka.go-generic/internal/demo"
)

func TestDemo(t *testing.T) {
	// demo.PublishAndConsumeNoGenerics()
}
