// Modified from code generated by github.com/wishabi/kafka.go.
package genericschemas

// "github.com/actgardner/gogen-avro/v7/compiler"
// "github.com/actgardner/gogen-avro/v7/vm"
// "github.com/actgardner/gogen-avro/v7/vm/types"
// "io"

// TODO: Move code from schema.go here for clarity that it uses generics.
